volumes:
  n8n_storage:
  postgres_storage:
  ollama_storage:
  qdrant_storage:
  open-webui:
  flowise:

networks:
  demo:

x-n8n: &service-n8n
  image: n8nio/n8n:latest
  networks: ['demo']
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_USER=${POSTGRES_USER}
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false
    - N8N_ENCRYPTION_KEY
    - N8N_USER_MANAGEMENT_JWT_SECRET
    - N8N_SECURE_COOKIE=false
  links:
    - postgres

x-ollama: &service-ollama
  image: ollama/ollama:latest
  networks: ['demo']
  restart: always

x-init-ollama: &init-ollama
  image: ollama/ollama:latest
  networks: ['demo']
  entrypoint: /bin/sh

services:
  flowise:
    image: flowiseai/flowise
    networks: ['demo']
    restart: unless-stopped
    container_name: flowise
    environment:
      - PORT=3001
    ports:
      - 3001:3001
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ~/.flowise:/root/.flowise
    entrypoint: /bin/sh -c "sleep 3; flowise start"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1g

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    networks: ['demo']
    restart: unless-stopped
    container_name: open-webui
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui:/app/backend/data
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1g

  postgres:
    image: postgres:16-alpine
    networks: ['demo']
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512m

  n8n-import:
    <<: *service-n8n
    container_name: n8n-import
    entrypoint: /bin/sh
    command:
      - "-c"
      - "n8n import:credentials --separate --input=/backup/credentials && n8n import:workflow --separate --input=/backup/workflows"
    volumes:
      - ./n8n/backup:/backup
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1g

  n8n:
    <<: *service-n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - 5678:5678
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./n8n/backup:/backup
      - ./shared:/data/shared
    depends_on:
      postgres:
        condition: service_healthy
      n8n-import:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2g

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    networks: ['demo']
    restart: unless-stopped
    ports:
      - 6333:6333
    volumes:
      - qdrant_storage:/qdrant/storage
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1g

  ollama-cpu-optimized:
    <<: *service-ollama
    container_name: ollama-cpu-optimized
    ports:
      - 11434:11434
    volumes:
      - ollama_storage:/root/.ollama
    deploy:
      resources:
        limits:
          cpus: "6.0"  # 6 von 8 Kernen
          memory: 14g  # 14 GB RAM für parallele Anfragen
    cpu_shares: 2048  # Höhere Priorität bei CPU-Konkurrenz
    environment:
      - OLLAMA_NUM_THREADS=6  # 6 Threads für maximale CPU-Nutzung

  ollama-pull-llama-cpu-optimized:
    <<: *init-ollama
    container_name: ollama-pull-llama-cpu-optimized
    volumes:
      - ollama_storage:/root/.ollama
    command:
      - "-c"
      - |
        sleep 15
        OLLAMA_HOST=ollama-cpu-optimized:11434 ollama pull llama3.1:8b
        OLLAMA_HOST=ollama-cpu-optimized:11434 ollama pull nomic-embed-text
    depends_on:
      - ollama-cpu-optimized
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512m
