FROM n8nio/runners:latest

USER root
RUN cd /opt/runners/task-runner-python \
    && uv pip install youtube-transcript-api
COPY n8n-task-runners.json /etc/n8n-task-runners.json
COPY n8n-task-runners.json /etc/task-runners.json
